env:
  commonjs: true
  es2021: true
  node: true
parser: '@typescript-eslint/parser'
extends:
  - 'eslint:recommended'
  - 'prettier'
  - 'plugin:@typescript-eslint/eslint-recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:@typescript-eslint/recommended-type-checked'
root: true
plugins:
  - '@typescript-eslint'
parserOptions:
  ecmaVersion: 'latest'
  project: 
    - 'tsconfig.json'
rules:
  # allow unused variables and parameters that start with '_'
  '@typescript-eslint/no-unused-vars':
    - 'error'
    - 'varsIgnorePattern': '^_'
      'argsIgnorePattern': '^_'
